SAMPLE_CLASSES = [
{
    "id": 13,
    "title": "Yoga Basics",
    "category": "Wellness",
    "description": "A gentle introduction to yoga fundamentals. Learn basic poses, breathing techniques, and mindfulness practices to improve flexibility and reduce stress.",
    "capacity": 15,
    "price": 12.0,
    "location": "Wellness Center, Studio A",
    "host": "Priya Sharma",
    "date": "2026-03-25",
    "time": "8:00 AM - 9:30 AM",
    "tags": ["yoga", "fitness", "wellness"],
    "photos": []
},
{
    "id": 24,
    "title": "Painting Workshop",
    "category": "Art",
    "description": "Explore the fundamentals of painting including color theory, brush techniques, and composition. Suitable for all skill levels looking to express their creativity on canvas.",
    "capacity": 12,
    "price": 20.0,
    "location": "Art Studio Downtown, Main Gallery",
    "host": "Carlos Rivera",
    "date": "2026-03-26",
    "time": "11:00 AM - 1:00 PM",
    "tags": ["art", "painting", "creative"],
    "photos": []
},
{
    "id": 35,
    "title": "Dance Starter",
    "category": "Dance",
    "description": "Get moving with this fun beginner dance class. Learn basic footwork, rhythm, and coordination through a variety of upbeat dance styles in a welcoming environment.",
    "capacity": 20,
    "price": 14.0,
    "location": "Dance Academy, Main Floor",
    "host": "Jasmine Lee",
    "date": "2026-03-27",
    "time": "6:00 PM - 7:30 PM",
    "tags": ["dance", "fitness", "fun"],
    "photos": []
},
    {
        "id": 1,
        "title": "Acrylic Painting for Beginners",
        "description": "Learn the fundamentals of acrylic painting on canvas. Perfect for beginners who want to express their creativity through vibrant colors and techniques.",
        "capacity": 12,
        "price": 18.0,
        "location": "Art Studio Downtown, Main Gallery",
        "host": "Maria Sanchez",
        "date": "2026-03-15",
        "time": "10:00 AM - 12:00 PM",
        "tags": ["Painting", "Art", "Beginner"],
        "photos": [
            "https://res.cloudinary.com/dkteitjxk/image/upload/v1709750000/classes/acrylic_painting_1.jpg",
            "https://res.cloudinary.com/dkteitjxk/image/upload/v1709750001/classes/acrylic_painting_2.jpg",
        ]
    },
    {
        "id": 2,
        "title": "Handmade Jewelry Design",
        "description": "Create beautiful jewelry pieces using beads, wires, and gemstones. Learn basic techniques for making necklaces, bracelets, and earrings.",
        "capacity": 10,
        "price": 22.0,
        "location": "Craft Center, Jewelry Workshop",
        "host": "Emma Thompson",
        "date": "2026-03-16",
        "time": "2:00 PM - 5:00 PM",
        "tags": ["Jewelry", "Craft", "Design"],
        "photos": [
            "https://res.cloudinary.com/dkteitjxk/image/upload/v1709750002/classes/jewelry_design_1.jpg",
        ]
    },
    {
        "id": 3,
        "title": "Ceramics and Pottery",
        "description": "Discover the art of working with clay. Learn hand-building techniques, glazing, and firing to create functional and decorative pottery pieces.",
        "capacity": 8,
        "price": 25.0,
        "location": "Pottery Studio, Wheel Room",
        "host": "David Chen",
        "date": "2026-03-17",
        "time": "9:00 AM - 12:00 PM",
        "tags": ["Ceramics", "Pottery", "Art"],
        "photos": [
            "https://res.cloudinary.com/dkteitjxk/image/upload/v1709750003/classes/ceramics_1.jpg",
            "https://res.cloudinary.com/dkteitjxk/image/upload/v1709750004/classes/ceramics_2.jpg",
            "https://res.cloudinary.com/dkteitjxk/image/upload/v1709750005/classes/ceramics_3.jpg",
        ]
    },
    {
        "id": 4,
        "title": "Watercolor Painting Workshop",
        "description": "Master the delicate art of watercolor painting. Explore color mixing, brush techniques, and creating beautiful landscapes and florals.",
        "capacity": 15,
        "price": 20.0,
        "location": "Art Academy, Watercolor Studio",
        "host": "Lisa Rodriguez",
        "date": "2026-03-18",
        "time": "1:00 PM - 4:00 PM",
        "tags": ["Painting", "Watercolor", "Art"],
        "photos": []
    },
    {
        "id": 5,
        "title": "Woodworking Basics",
        "description": "Learn fundamental woodworking skills including measuring, cutting, sanding, and joining. Create your own wooden projects and furniture pieces.",
        "capacity": 6,
        "price": 28.0,
        "location": "Woodshop Community Center, Workshop A",
        "host": "James Wilson",
        "date": "2026-03-19",
        "time": "10:00 AM - 1:00 PM",
        "tags": ["Woodworking", "Craft", "DIY"],
        "photos": []
    },
    {
        "id": 6,
        "title": "Knitting and Textile Arts",
        "description": "Explore the world of fiber arts including knitting, crocheting, and weaving. Create scarves, hats, and other wearable textile pieces.",
        "capacity": 14,
        "price": 15.0,
        "location": "Textile Studio, Fiber Arts Room",
        "host": "Sarah Johnson",
        "date": "2026-03-20",
        "time": "3:00 PM - 6:00 PM",
        "tags": ["Knitting", "Textile", "Craft"],
        "photos": []
    },
    {
        "id": 7,
        "title": "Glass Bead Making",
        "description": "Learn to create beautiful glass beads using a torch and glass rods. Design and make your own unique jewelry components.",
        "capacity": 8,
        "price": 24.0,
        "location": "Glass Arts Center, Torch Room",
        "host": "Mike Patterson",
        "date": "2026-03-21",
        "time": "9:00 AM - 12:00 PM",
        "tags": ["Glass", "Jewelry", "Craft"],
        "photos": []
    },
    {
        "id": 8,
        "title": "Calligraphy and Hand Lettering",
        "description": "Master the art of beautiful handwriting and lettering. Learn various scripts, tools, and techniques for creating stunning calligraphy pieces.",
        "capacity": 12,
        "price": 19.0,
        "location": "Lettering Studio, Calligraphy Room",
        "host": "Nina Patel",
        "date": "2026-03-22",
        "time": "2:00 PM - 5:00 PM",
        "tags": ["Calligraphy", "Writing", "Art"],
        "photos": []
    },
    {
        "id": 9,
        "title": "Mixed Media Art",
        "description": "Combine various art mediums including paint, collage, found objects, and more to create unique mixed media artworks and installations.",
        "capacity": 10,
        "price": 21.0,
        "location": "Contemporary Art Space, Mixed Media Studio",
        "host": "Alex Martinez",
        "date": "2026-03-23",
        "time": "10:00 AM - 1:00 PM",
        "tags": ["Mixed Media", "Art", "Creative"],
        "photos": []
    },
    {
        "id": 10,
        "title": "Sculpture with Clay",
        "description": "Explore three-dimensional art through clay sculpture. Learn modeling techniques, texturing, and finishing methods for creating sculptures.",
        "capacity": 7,
        "price": 23.0,
        "location": "Sculpture Workshop, Modeling Studio",
        "host": "Rachel Green",
        "date": "2026-03-24",
        "time": "1:00 PM - 4:00 PM",
        "tags": ["Sculpture", "Clay", "Art"],
        "photos": []
    },
        {
        "id": 11,
        "title": "Fire Dance",
        "description": "fire dance",
        "capacity": 7,
        "price": 23.0,
        "location": "Sculpture Workshop, Modeling Studio",
        "host": "Rachel Green",
        "date": "2026-03-24",
        "time": "1:00 PM - 4:00 PM",
        "tags": ["Dance", "Clay", "Art"],
        "photos": [],
        "trendy": True
    },
]